

package TradeX;
import static TradeX.ilkekran.tabular;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.ResultSet;
import  java.text.SimpleDateFormat;
import java.util.Date;
import java.text.ParseException;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.hibernate.Hibernate;
import org.jdesktop.swingx.calendar.DateUtils;
/**
 *
 * @author seckin.celik
 */
public class cenc extends javax.swing.JInternalFrame {

    /**
     * Creates new form ilkEkran
     */
    Object data[][]=null;
    String [] columnNames=new String[9];
    String [] columnName=new String[13];
    String pdfName="";String contractName;
    int pdfSize=0;int contractsize=0;
    FileInputStream fis=null;
    File nf=null;
    java.sql.Blob pdF;
   static double ilave=0;
   java.sql.Date dFrom;java.sql.Date dTo;
   int j=0;
    public cenc(int i) {
        j=i;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        target_price = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        capacityy = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        seller1 = new javax.swing.JTextField();
        buyer1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        deal_start = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        deal_end = new org.jdesktop.swingx.JXDatePicker();
        payment_date = new org.jdesktop.swingx.JXDatePicker();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        tr_tr1 = new javax.swing.JRadioButton();
        bg_tr1 = new javax.swing.JRadioButton();
        gr_tr1 = new javax.swing.JRadioButton();
        tr_gr1 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        stamp_buyer1 = new javax.swing.JCheckBox();
        stamp_seller1 = new javax.swing.JCheckBox();
        stamp_half1 = new javax.swing.JCheckBox();
        stamp_nap1 = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        fxRate = new javax.swing.JTextField();
        creditInterest = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jToolBar3 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        export = new javax.swing.JTextField();
        perimeter = new javax.swing.JTextField();
        suf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cbtc = new javax.swing.JTextField();
        brokerage = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tloss = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        validity_date = new org.jdesktop.swingx.JXDatePicker();
        amount = new javax.swing.JTextField();
        commission = new javax.swing.JTextField();
        issue_date = new org.jdesktop.swingx.JXDatePicker();
        jPanel11 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Star Date"));
        setClosable(true);
        setForeground(java.awt.Color.pink);
        setIconifiable(true);
        setTitle(ilkekran.tabular.getValueAt(ilkekran.tabular.getSelectedRow(),0).toString());
        setAutoscrolls(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/1391713225_Terms-rev.png"))); // NOI18N
        setNormalBounds(new java.awt.Rectangle(1000, 1000, 127, 0));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Deal Side (1)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel1.setText("Seller");

        jLabel2.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel2.setText("Buyer");

        jLabel6.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel6.setText("Type");

        type.setBackground(new java.awt.Color(204, 204, 255));
        type.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bilateral", "Spot", "Asset", "Access" }));

        jLabel17.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel17.setText(" Price");

        target_price.setBackground(new java.awt.Color(255, 255, 204));
        target_price.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        target_price.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel26.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel26.setText("Capacity");

        capacityy.setEditable(false);
        capacityy.setBackground(new java.awt.Color(255, 255, 204));
        capacityy.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        capacityy.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        capacityy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacityyActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel15.setText("Target Price");

        jTextField1.setBackground(new java.awt.Color(255, 255, 204));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jComboBox6.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TRY", "EUR", "USD" }));

        jComboBox8.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TRY", "EUR", "USD" }));

        jLabel24.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel24.setText("MW");

        seller1.setBackground(new java.awt.Color(255, 255, 204));
        seller1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        seller1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        buyer1.setBackground(new java.awt.Color(255, 255, 204));
        buyer1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        buyer1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seller1)
                            .addComponent(buyer1)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel26)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(target_price, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                    .addComponent(capacityy))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(seller1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(buyer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(target_price)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(capacityy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 220, 270));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date (2)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.red));
        jPanel4.setForeground(new java.awt.Color(204, 204, 255));

        deal_start.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel3.setText("Start");

        jLabel5.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel5.setText("End");

        deal_end.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        payment_date.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel13.setText("Pay");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deal_end, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payment_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deal_start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(93, 93, 93))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deal_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(deal_end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payment_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 240, 160));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Direction (4)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.red));

        tr_tr1.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(tr_tr1);
        tr_tr1.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        tr_tr1.setText("TR>TR");

        bg_tr1.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(bg_tr1);
        bg_tr1.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        bg_tr1.setText("BG>TR");
        bg_tr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bg_tr1ActionPerformed(evt);
            }
        });

        gr_tr1.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(gr_tr1);
        gr_tr1.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        gr_tr1.setText("GR>TR");

        tr_gr1.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(tr_gr1);
        tr_gr1.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        tr_gr1.setText("TR>GR");

        jRadioButton1.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jRadioButton1.setText("TR>BG");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tr_tr1)
                    .addComponent(bg_tr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gr_tr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tr_gr1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(tr_tr1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bg_tr1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gr_tr1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tr_gr1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 80, 260));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stamp Fee (5)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.red));

        stamp_buyer1.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(stamp_buyer1);
        stamp_buyer1.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        stamp_buyer1.setText("Buyer");

        stamp_seller1.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(stamp_seller1);
        stamp_seller1.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        stamp_seller1.setText("Seller");

        stamp_half1.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(stamp_half1);
        stamp_half1.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        stamp_half1.setText("Half");

        stamp_nap1.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(stamp_nap1);
        stamp_nap1.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        stamp_nap1.setText("N/A");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stamp_buyer1)
                            .addComponent(stamp_seller1)
                            .addComponent(stamp_nap1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(stamp_half1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(stamp_buyer1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stamp_seller1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stamp_half1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stamp_nap1)
                .addGap(47, 47, 47))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 100, 260));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Financing (9)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.red));

        fxRate.setBackground(new java.awt.Color(255, 255, 204));
        fxRate.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        fxRate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        creditInterest.setBackground(new java.awt.Color(255, 255, 204));
        creditInterest.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        creditInterest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel11.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel11.setText("FX Forward Rate");

        jLabel12.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel12.setText("Credit Interest");

        jToolBar3.setBorder(null);
        jToolBar3.setFloatable(false);
        jToolBar3.setRollover(true);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/refresh.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 4, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fxRate, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                    .addComponent(creditInterest)))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fxRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(creditInterest)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(0, 124, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 170, 290));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TSO (6)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.red));

        jLabel8.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel8.setText("Export");

        jLabel9.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel9.setText("Perimeter");

        jLabel10.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel10.setText("SUF");

        export.setBackground(new java.awt.Color(255, 255, 204));
        export.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        export.setToolTipText("Perimeter and all relevant cost per MW energy");
        export.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        perimeter.setBackground(new java.awt.Color(255, 255, 204));
        perimeter.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        perimeter.setToolTipText("Cross Border Capacity Cost if it applies - default 0");
        perimeter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        suf.setBackground(new java.awt.Color(255, 255, 204));
        suf.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        suf.setToolTipText("System Usage Fee");
        suf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        suf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sufActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel14.setText("CBTC");

        jLabel18.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel18.setText("Brokerage");

        cbtc.setBackground(new java.awt.Color(255, 255, 204));
        cbtc.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cbtc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        brokerage.setBackground(new java.awt.Color(255, 255, 204));
        brokerage.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        brokerage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel25.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel25.setText("T/L");

        tloss.setBackground(new java.awt.Color(255, 255, 204));
        tloss.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        tloss.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EUR", "TRY", "USD" }));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EUR", "TRY", "USD" }));

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EUR", "TRY", "USD" }));

        jComboBox4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EUR", "TRY", "USD" }));

        jComboBox5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EUR", "TRY", "USD" }));

        jLabel28.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel28.setText("FX CBTC");

        jTextField5.setBackground(new java.awt.Color(255, 255, 204));
        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10)
                        .addComponent(jLabel8)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel25))
                    .addComponent(jLabel28))
                .addGap(34, 34, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brokerage, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(export, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perimeter, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbtc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tloss, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox2, 0, 54, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {brokerage, cbtc, export, jTextField5, perimeter, suf, tloss});

        jPanel9Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel14, jLabel18, jLabel25, jLabel28, jLabel8, jLabel9});

        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(export, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(perimeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(suf)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(cbtc, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(brokerage)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(tloss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {export, jLabel8});

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel9, perimeter});

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, suf});

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel25, tloss});

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel28, jTextField5});

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 220, 280));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bank  Guarantee (7)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 51, 0)));

        jLabel20.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel20.setText("Amount");

        jLabel21.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel21.setText("Commission");

        jLabel22.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel22.setText("Validity");

        jLabel23.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel23.setText("Issue Date");

        validity_date.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        amount.setBackground(new java.awt.Color(255, 255, 204));
        amount.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        amount.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        commission.setBackground(new java.awt.Color(255, 255, 204));
        commission.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        commission.setToolTipText("Quarterly commission percentage");
        commission.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        issue_date.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(validity_date, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(issue_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(amount, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(commission))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(validity_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(issue_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 250, 190));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Schedule (3)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 0, 0)));
        jPanel11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N

        buttonGroup3.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Batang", 0, 11)); // NOI18N
        jRadioButton2.setText("Base");

        buttonGroup3.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Batang", 0, 11)); // NOI18N
        jRadioButton3.setText("Irregular");

        buttonGroup4.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jRadioButton4.setText("Non-tariff Index");

        buttonGroup4.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jRadioButton5.setText("Tariff-Indexed");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addContainerGap())
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 240, 100));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Commission (8)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 0, 0)));

        jLabel19.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel19.setText("Broker Name");

        jLabel27.setFont(new java.awt.Font("Batang", 0, 10)); // NOI18N
        jLabel27.setText("Rate");

        jTextField4.setBackground(new java.awt.Color(255, 255, 204));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTextField2.setBackground(new java.awt.Color(255, 255, 204));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel27))
                .addGap(36, 36, 36)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jTextField2))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 250, 100));

        jTabbedPane1.addTab("Deal Save", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    
    
    
    
    
    
    private void sufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sufActionPerformed

    private void bg_tr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bg_tr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bg_tr1ActionPerformed

    private void capacityyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacityyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capacityyActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        dbo.dealSave dealID=new dbo.dealSave();
      
       ResultSet idl=dealID.view(j);
       
       try{
           while(idl.next()){
               seller1.setText(idl.getString("Seller"));
               buyer1.setText(idl.getString("Buyer"));
               target_price.setText(""+idl.getDouble("PriceBrut"));
               capacityy.setText(""+idl.getDouble("Capacity"));
               deal_start.setDate(idl.getDate("Start_Date"));
               deal_end.setDate(idl.getDate("End_Date"));
               export.setText(""+idl.getDouble("Export"));
               perimeter.setText(""+idl.getDouble("Perimeter"));
               suf.setText(""+idl.getDouble("Suf"));
               cbtc.setText(""+idl.getDouble("Cbtc"));
               tloss.setText(""+idl.getDouble("Tloss"));
               jTextField5.setText(""+idl.getDouble("FxCBTC"));
               payment_date.setDate(idl.getDate("Payment_Date"));
               amount.setText(""+idl.getDouble("Amount"));
               validity_date.setDate(idl.getDate("Validity"));
               issue_date.setDate(idl.getDate("Issue"));
              
               if("Base".equals(idl.getString("Profile"))){
               jRadioButton2.setSelected(true);
               }else{
                   jRadioButton3.setSelected(true);
               }
               fxRate.setText(""+idl.getDouble("Exchnge"));
               creditInterest.setText(""+idl.getDouble("credit"));
               if("Non-tariff Index".equals(idl.getString("PriceIndex"))){
               jRadioButton4.setSelected(true);}
               else{
               jRadioButton5.setSelected(true);
               }
               tr_tr1.setSelected(false);bg_tr1.setSelected(false);gr_tr1.setSelected(false);tr_gr1.setSelected(false);jRadioButton1.setSelected(false);
               switch (idl.getString("Direction")) {
                   case "TR>TR":
                       tr_tr1.setSelected(true);
                       break;
                   case "BG>TR":
                       bg_tr1.setSelected(true);
                       break;
                   case "GR>TR":
                       gr_tr1.setSelected(true);
                       break;
                   case "TR>GR":
                       tr_gr1.setSelected(true);
                       break;
                   default:
                       jRadioButton1.setSelected(true);
                       break;
               }
               jTextField4.setText(""+idl.getDouble("BrokerRate"));
               jTextField2.setText(idl.getString("BrokerName"));                   
               commission.setText(""+idl.getDouble("Commission"));
               stamp_half1.setSelected(false); stamp_buyer1.setSelected(false);stamp_seller1.setSelected(false);stamp_nap1.setSelected(false);
               switch (idl.getString("Stamp")) {
                   case "Half":
                       stamp_half1.setSelected(true);
                       break;
                   case "Buyer":
                       stamp_buyer1.setSelected(true);
                       break;
                   case "GFI":
                       stamp_seller1.setSelected(true);
                       break;

                   default:
                       stamp_nap1.setSelected(true);
                       break;
               }
         }
       }catch(SQLException e){}
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String seller="";String buyer="";String type1="";String schedule_profile;String yon;
        double export_fee;double suf_fee;double perimetric_fee; double cbtc_fee; double transmissionloss_ratio;double fxcbtc_fee;
        String tarife="";String stamp_fee="";double capacity;
        double bankcommissionAmount;double bankcommissionRate;String brokerName;double brokerRate;
        double commision;double exchangeRate;
        capacity=Double.parseDouble(capacityy.getText());
        SimpleDateFormat tarihFormat = new SimpleDateFormat("dd/MM/yyyy");
        String date_from_store1 = tarihFormat.format(deal_start.getDate()).toString();
        String date_to_store1 = tarihFormat.format(deal_end.getDate()).toString();
        String date_payment_store1 = tarihFormat.format(payment_date.getDate()).toString();
        String date_validity_store1 = tarihFormat.format(validity_date.getDate()).toString();
        String date_issue_store1 = tarihFormat.format(issue_date.getDate()).toString();
        java.sql.Date dFroms=null;java.sql.Date dTos=null;java.sql.Date dPayments=null;java.sql.Date dValiditys=null;
        java.sql.Date dIssues=null;
        try {
             dFroms= new java.sql.Date(tarihFormat.parse(date_from_store1).getTime());
            
        } catch (ParseException ex) {
            Logger.getLogger(cenc.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            dTos= new java.sql.Date(tarihFormat.parse(date_to_store1).getTime());
            
        } catch (ParseException ex) {
            Logger.getLogger(cenc.class.getName()).log(Level.SEVERE, null, ex);
        }
         try {
            dPayments= new java.sql.Date(tarihFormat.parse(date_payment_store1).getTime());
            
        } catch (ParseException ex) {
            Logger.getLogger(cenc.class.getName()).log(Level.SEVERE, null, ex);
        }
         try {
            dValiditys= new java.sql.Date(tarihFormat.parse(date_validity_store1).getTime());
            
        } catch (ParseException ex) {
            Logger.getLogger(cenc.class.getName()).log(Level.SEVERE, null, ex);
        }
         try {
            dIssues= new java.sql.Date(tarihFormat.parse(date_issue_store1).getTime());
            
        } catch (ParseException ex) {
            Logger.getLogger(cenc.class.getName()).log(Level.SEVERE, null, ex);
        }
        seller=seller1.getText();
        buyer=buyer1.getText();
        type1=type.getSelectedItem().toString();
        export_fee=Double.parseDouble(export.getText());
        suf_fee=Double.parseDouble(suf.getText());
        perimetric_fee=Double.parseDouble(perimeter.getText());
        cbtc_fee=Double.parseDouble(cbtc.getText());
        transmissionloss_ratio=Double.parseDouble(tloss.getText());
        fxcbtc_fee=Double.parseDouble(jTextField5.getText());
  
        if(jRadioButton2.isSelected()){
            schedule_profile="Base";
         }
        else{
            schedule_profile="Irregular";
        }
        if(jRadioButton4.isSelected()){
            tarife=jRadioButton4.getText();
        }
        else{
            tarife=jRadioButton5.getText();
        }
        
        if(tr_tr1.isSelected()){
            yon=tr_tr1.getText();
        }
        else if(bg_tr1.isSelected()){
            yon=bg_tr1.getText();
        }
        else if(gr_tr1.isSelected()){
            yon=gr_tr1.getText();
        }
        else if(tr_gr1.isSelected()){
            yon=tr_gr1.getText();
        }
        else{
            yon=jRadioButton1.getText();
        }
        if(stamp_buyer1.isSelected()){
            stamp_fee=stamp_buyer1.getText();
        }
        else if(stamp_seller1.isSelected()){
        stamp_fee=stamp_seller1.getText();
        }
        else if(stamp_half1.isSelected()){
            stamp_fee=stamp_half1.getText();
        }
        else{
            stamp_fee=stamp_nap1.getText();
        }
        bankcommissionAmount=Double.parseDouble(amount.getText());
        bankcommissionRate=Double.parseDouble(commission.getText());
        brokerName=jTextField2.getText();
        brokerRate=Double.parseDouble(jTextField4.getText());
        commision=Double.parseDouble(creditInterest.getText());
        exchangeRate=Double.parseDouble(fxRate.getText());
        dbo.dealSave updatedeal=new dbo.dealSave();
        
        updatedeal.alter(seller1.getText(), buyer1.getText(), type.getSelectedItem().toString(),dFroms,0,dTos,0,yon,stamp_fee,capacity,capacity*hoursBetween((java.util.Date)dFroms ,(java.util.Date)dTos,0,0),Double.parseDouble(target_price.getText()),0.0,0.0,Double.parseDouble(export.getText()),Double.parseDouble(suf.getText()),Double.parseDouble(perimeter.getText()),Double.parseDouble(tloss.getText()),Double.parseDouble(cbtc.getText()),Double.parseDouble(fxRate.getText()),Double.parseDouble(creditInterest.getText()),dPayments,0,dIssues,dValiditys,brokerName,Double.parseDouble(jTextField4.getText()),Double.parseDouble(target_price.getText())*Double.parseDouble(jTextField4.getText()),schedule_profile,tarife,bankcommissionRate,Integer.parseInt(this.getTitle()));
        this.dispose();
        
        int li_row = 0;
       String columnName1[]=new String [] {
                "ID", "Seller", "Buyer", "Type", "Start_Date", "Start_Hr", "End_Date", "End_Hr", "Direction", "Stamp","Capacity","Energy",
            "Price", "BrutPrice", "Expense","Export","SUF","Perimeter","Tloss","Cbtc","FX","Credit","Payment_Date","Payment_Hr","Validity",
            "Issue","Brokerage","Commission","Amount"
            };
        try{
            dbo.dealSave input=new dbo.dealSave();
            ResultSet abc=input.qry();
            
            while(abc.next()){               
                li_row++;
        }
            Object data1[][] =new Object[li_row][29];            
            li_row=0;            abc=input.qry();

            while(abc.next()){
                data1[li_row][0]=abc.getInt("id");
                data1[li_row][1]=abc.getString("Seller");
                data1[li_row][2]=abc.getString("Buyer");
                data1[li_row][3]=abc.getString("Typy");
                data1[li_row][4]=abc.getDate("Start_Date");
                data1[li_row][5]=abc.getInt("Start_Hr");
                data1[li_row][6]=abc.getDate("End_Date");
                data1[li_row][7]=abc.getInt("End_Hr");
                data1[li_row][8]=abc.getString("Direction");
                data1[li_row][9]=abc.getString("Stamp");
                data1[li_row][10]=abc.getDouble("Capacity");
                data1[li_row][11]=abc.getString("Energy");
                data1[li_row][12]=abc.getDouble("Price");
                data1[li_row][13]=abc.getDouble("PriceBrut");
                data1[li_row][14]=abc.getDouble("Expense");
                data1[li_row][15]=abc.getDouble("Export");
                data1[li_row][16]=abc.getDouble("Suf");
                data1[li_row][17]=abc.getDouble("Perimeter");
                data1[li_row][18]=abc.getDouble("Tloss");
                data1[li_row][19]=abc.getDouble("Cbtc");
                data1[li_row][20]=abc.getDouble("Exchnge");
                data1[li_row][21]=abc.getDouble("credit");
                data1[li_row][22]=abc.getDate("Payment_Date");
                data1[li_row][23]=abc.getInt("Payment_Hr");
                data1[li_row][24]=abc.getDate("Validity");
                data1[li_row][25]=abc.getDate("Issue");
                data1[li_row][26]=abc.getDouble("Brokerage");
                data1[li_row][27]=abc.getDouble("Commission");
                data1[li_row][28]=abc.getDouble("Amount");

                     li_row++;
        }

             tabular.setModel(new DefaultTableModel(data1,columnName1));                           
            
        }
        catch(SQLException e){}
     
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    public double hoursBetween(Date d1, Date d2,int h1,int h2){
        return (double)(((d2.getTime() - d1.getTime()) / (1000 * 60 * 60))+h1-h2);
     }
public int daysBetween(Date d1, Date d2){
return (int)(((d2.getTime() - d1.getTime()) / (1000 * 60 * 60*24)));
}
public static boolean isMyResultSetEmpty(ResultSet rs) throws SQLException {
    return (!rs.isBeforeFirst() && rs.getRow() == 0);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JRadioButton bg_tr1;
    private javax.swing.JTextField brokerage;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTextField buyer1;
    public static javax.swing.JTextField capacityy;
    private javax.swing.JTextField cbtc;
    private javax.swing.JTextField commission;
    private javax.swing.JTextField creditInterest;
    private org.jdesktop.swingx.JXDatePicker deal_end;
    private org.jdesktop.swingx.JXDatePicker deal_start;
    private javax.swing.JTextField export;
    private javax.swing.JTextField fxRate;
    private javax.swing.JRadioButton gr_tr1;
    private org.jdesktop.swingx.JXDatePicker issue_date;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToolBar jToolBar3;
    private org.jdesktop.swingx.JXDatePicker payment_date;
    private javax.swing.JTextField perimeter;
    private javax.swing.JTextField seller1;
    private javax.swing.JCheckBox stamp_buyer1;
    private javax.swing.JCheckBox stamp_half1;
    private javax.swing.JCheckBox stamp_nap1;
    private javax.swing.JCheckBox stamp_seller1;
    private javax.swing.JTextField suf;
    private javax.swing.JTextField target_price;
    private javax.swing.JTextField tloss;
    private javax.swing.JRadioButton tr_gr1;
    private javax.swing.JRadioButton tr_tr1;
    private javax.swing.JComboBox type;
    private org.jdesktop.swingx.JXDatePicker validity_date;
    // End of variables declaration//GEN-END:variables
}
