/*
 *  This software is designed for Unit Electric
 *  Contact seckin.celik@unitelektrik.com.tr
 * 
 */

package TradeX;

import java.awt.HeadlessException;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author seckin.celik
 */
public class dealsearch extends javax.swing.JInternalFrame {

                    String a="";
                Connection conn = null;
		Statement stmt = null;
		ResultSet rs = null;
                PreparedStatement ps=null;
                private String connectionUrl="jdbc:mysql://192.168.0.162:3306/unit";
                private String connectionUser="general_user";
                private String connectionPassword= "Trade2013.";
    public dealsearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        contract = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablo = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/open1616.png"))); // NOI18N
        jMenu1.setText("Open");
        jMenu1.setToolTipText("");

        contract.setText("Contract");
        contract.setToolTipText("");
        contract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contractview(evt);
            }
        });
        jMenu1.add(contract);

        jMenuItem2.setText(" B/G");
        jMenuItem2.setToolTipText("");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgview(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("view CBTC Contract");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText(" Energy Invoice");
        jMenuItem4.setToolTipText("");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText(" LFC");
        jMenuItem5.setToolTipText("");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewlfc(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText(" CBTC Invoice");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jPopupMenu1.add(jMenu1);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/Money1616.png"))); // NOI18N
        jMenuItem1.setText("Profit");
        jMenuItem1.setToolTipText("");
        jPopupMenu1.add(jMenuItem1);

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setForeground(java.awt.Color.white);
        setIconifiable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1344, 617));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Deals"));

        tablo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Seller", "Buyer", "Start", "End", "Payment", "B/G Issue", "B/G Validity", "Contract", "B/G", "LFC"
            }
        ));
        tablo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabloMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabloMouseReleased(evt);
            }
        });
        tablo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabloKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabloKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Previous Deals"));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Seller", "Buyer", "Start", "End"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addGap(24, 24, 24))
        );

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton1.setText("All");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton2.setText("Last Month");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton4.setText("This Month");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton3.setText("Next Month");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/refresh2020.png"))); // NOI18N
        jButton1.setToolTipText("Re-load Deals");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/search2020.png"))); // NOI18N

        jTextField1.setBackground(new java.awt.Color(255, 255, 204));
        jTextField1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/Opennew.png"))); // NOI18N
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2)
                                .addGap(24, 24, 24)
                                .addComponent(jRadioButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(132, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton4)
                        .addComponent(jRadioButton3))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(388, 388, 388))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(598, 598, 598))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
                tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabloMouseReleased(evt);
            }
        });
        tablo.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabloKeyReleased(evt);
            }
        });
        jRadioButton1.setSelected(true);
        int i=0;

        dbo.dealSave deal=new dbo.dealSave();
        int j=deal.monthvieww();

        ResultSet rss=deal.monthview();
        
        String [] kolonname={"Select","ID","Seller","Buyer","Start","End","Payment","BG Issue","BG Validity","Contract","BG","LFC"};
        Object veri[][]=new Object[j][12];
        try {
            while(rss.next()){
                veri[i][1]=rss.getInt("id");
                veri[i][2]=rss.getString("Seller");
                veri[i][3]=rss.getString("Buyer");
                veri[i][4]=rss.getDate("Start_Date");
                veri[i][5]=rss.getDate("End_Date");
                veri[i][6]=rss.getDate("Payment_Date");
                veri[i][7]=rss.getDate("Issue");
                veri[i][8]=rss.getDate("Validity");
                veri[i][9]=rss.getString("ContractName");
                veri[i][10]=rss.getString("Filename");           
                veri[i][11]=rss.getString("LFCName");           
      

                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(dealsearch.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        tablo.setModel(new DefaultTableModel(veri,kolonname)
                    {
            Class[] types = new Class [] {
                java.lang.Boolean.class,java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        
        jScrollPane1.setViewportView(tablo);
    }//GEN-LAST:event_formInternalFrameOpened

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
         String columnName[]={"Select","ID","Seller","Buyer","Start","End","Payment","BG Issue","BG Validity","Contract","BG","LFC"};
        
        dbo.dealSave isimCek=new dbo.dealSave();      

        ResultSet rs1=isimCek.keyevent(jTextField1.getText());
         
        int li=0; 
        
         
         
             try {
                 while(rs1.next()){
//                      oss[li][1]=rs1.getInt("id");
//                      oss[li][2]=rs1.getString("Seller");
//                      oss[li][3]=rs1.getString("Buyer");
//                      oss[li][4]=rs1.getDate("Start_Date");
//                      oss[li][5]=rs1.getDate("End_Date");
//                      oss[li][6]=rs1.getDate("Payment_Date");
//                      oss[li][7]=rs1.getDate("Issue");
//                      oss[li][8]=rs1.getDate("Validity");
//                      oss[li][9]=rs1.getString("ContractName");
//                      oss[li][10]=rs1.getString("Filename");
                     
                     li++;
                 }    } catch (SQLException ex) {
                 Logger.getLogger(dealsearch.class.getName()).log(Level.SEVERE, null, ex);
             }
              Object oss[][]=new Object[li][12];
              
              li=0;
              ResultSet rs2=isimCek.keyevent(jTextField1.getText());
              try {
                    while(rs2.next()){
                      oss[li][1]=rs2.getInt("id");
                      oss[li][2]=rs2.getString("Seller");
                      oss[li][3]=rs2.getString("Buyer");
                      oss[li][4]=rs2.getDate("Start_Date");
                      oss[li][5]=rs2.getDate("End_Date");
                      oss[li][6]=rs2.getDate("Payment_Date");
                      oss[li][7]=rs2.getDate("Issue");
                      oss[li][8]=rs2.getDate("Validity");
                      oss[li][9]=rs2.getString("ContractName");
                      oss[li][10]=rs2.getString("Filename");
                      oss[li][11]=rs2.getString("LFCName");

                        li++;
        }

 tablo.setModel(new DefaultTableModel(oss,columnName)
                    {
            Class[] types = new Class [] {
                java.lang.Boolean.class,java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });       
            } catch (SQLException ex) {
                    System.out.println(ex.toString());
    }
            finally {
			try { if (rs1 != null) rs1.close(); } catch (SQLException e) {
                            System.out.println(e.toString());
                    }

		}
        
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
               jTextField1.setText("");

        tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabloMouseReleased(evt);
            }
        });
        tablo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabloKeyReleased(evt);
            }
        });
        String columnName[]={"Select","ID","Seller","Buyer","Start","End","Payment","BG Issue","BG Validity","Contract","BG","LFC"};
        int i=0;
        dbo.dealSave nextmonth=new dbo.dealSave();
        int j=nextmonth.monthvieww3();
        ResultSet mont=nextmonth.monthNext();
        Object oss[][]=new Object[j][12];

                    try {
                    while(mont.next()){
                      oss[i][1]=mont.getInt("id");
                      oss[i][2]=mont.getString("Seller");
                      oss[i][3]=mont.getString("Buyer");
                      oss[i][4]=mont.getDate("Start_Date");
                      oss[i][5]=mont.getDate("End_Date");
                      oss[i][6]=mont.getDate("Payment_Date");
                      oss[i][7]=mont.getDate("Issue");
                      oss[i][8]=mont.getDate("Validity");
                      oss[i][9]=mont.getString("ContractName");
                      oss[i][10]=mont.getString("Filename");
                      oss[i][11]=mont.getString("LFCName");
                      
                        i++;
        }
                    }catch(SQLException e){}     
                    
                     tablo.setModel(new DefaultTableModel(oss,columnName)
                    {
            Class[] types = new Class [] {
                java.lang.Boolean.class,java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        
        jScrollPane1.setViewportView(tablo);
                    tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabloMouseReleased(evt);
            }
        });
        tablo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabloKeyReleased(evt);
            }
        });
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
                jTextField1.setText("");
       
        tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabloMouseReleased(evt);
            }
        });
        tablo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabloKeyReleased(evt);
            }
        });
                 String columnName[]={"Select","ID","Seller","Buyer","Start","End","Payment","BG Issue","BG Validity","Contract","BG","LFC"};
        int i=0;
        dbo.dealSave nextmonth=new dbo.dealSave();
                int j=nextmonth.monthvieww1();

        ResultSet mont=nextmonth.previousmonth();
                Object oss[][]=new Object[j][12];

                    try {
                    while(mont.next()){
                      oss[i][1]=mont.getInt("id");
                      oss[i][2]=mont.getString("Seller");
                      oss[i][3]=mont.getString("Buyer");
                      oss[i][4]=mont.getDate("Start_Date");
                      oss[i][5]=mont.getDate("End_Date");
                      oss[i][6]=mont.getDate("Payment_Date");
                      oss[i][7]=mont.getDate("Issue");
                      oss[i][8]=mont.getDate("Validity");
                      oss[i][9]=mont.getString("ContractName");
                      oss[i][10]=mont.getString("Filename");
                      oss[i][11]=mont.getString("LFCName");
                      
                        i++;
        }
                    }catch(Exception e){}              
                     tablo.setModel(new DefaultTableModel(oss,columnName)
                    {
            Class[] types = new Class [] {
                java.lang.Boolean.class,java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        
        jScrollPane1.setViewportView(tablo);
                    
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed

        // TODO add your handling code here:
                jTextField1.setText("");

        tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabloMouseReleased(evt);
            }
        });
        tablo.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabloKeyReleased(evt);
            }
        });
        
         String columnName[]={"Select","ID","Seller","Buyer","Start","End","Payment","BG Issue","BG Validity","Contract","BG","LFC"};
        int i=0;
        dbo.dealSave nextmonth1=new dbo.dealSave();
        int j=nextmonth1.monthvieww2();
        ResultSet mont2=nextmonth1.currentmonth();
        
        Object oss[][]=new Object[j][12];
                    try {
                    while(mont2.next()){
                      oss[i][1]=mont2.getInt("id");
                      oss[i][2]=mont2.getString("Seller");
                      oss[i][3]=mont2.getString("Buyer");
                      oss[i][4]=mont2.getDate("Start_Date");
                      oss[i][5]=mont2.getDate("End_Date");
                      oss[i][6]=mont2.getDate("Payment_Date");
                      oss[i][7]=mont2.getDate("Issue");
                      oss[i][8]=mont2.getDate("Validity");
                      oss[i][9]=mont2.getString("ContractName");
                      oss[i][10]=mont2.getString("Filename");
                        oss[i][11]=mont2.getString("LFCName");                     
                        i++;
        }
                    }catch(SQLException e){}              
                     tablo.setModel(new DefaultTableModel(oss,columnName)
                    {
            Class[] types = new Class [] {
                java.lang.Boolean.class,java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        
        jScrollPane1.setViewportView(tablo);
                    
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabloMouseReleased(evt);
            }
        });
        tablo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabloKeyReleased(evt);
            }
        });
         
        int i=0;
        dbo.dealSave nextmonth=new dbo.dealSave();
        ResultSet mont=nextmonth.monthview();
        int j=nextmonth.monthvieww();
        String columnName[]={"Select","ID","Seller","Buyer","Start","End","Payment","BG Issue","BG Validity","Contract","BG","LFC"};
        Object oss[][]=new Object[j][12];
                    try {
                    while(mont.next()){
                      oss[i][1]=mont.getInt("id");
                      oss[i][2]=mont.getString("Seller");
                      oss[i][3]=mont.getString("Buyer");
                      oss[i][4]=mont.getDate("Start_Date");
                      oss[i][5]=mont.getDate("End_Date");
                      oss[i][6]=mont.getDate("Payment_Date");
                      oss[i][7]=mont.getDate("Issue");
                      oss[i][8]=mont.getDate("Validity");
                      oss[i][9]=mont.getString("ContractName");
                      oss[i][10]=mont.getString("Filename");
                      oss[i][11]=mont.getString("LFCName");
                      
                        i++;
        }
                    }catch(SQLException e){}              

                     tablo.setModel(new DefaultTableModel(oss,columnName)
                    {
            Class[] types = new Class [] {
                java.lang.Boolean.class,java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        
        jScrollPane1.setViewportView(tablo);
                    
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void contractview(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contractview
        // TODO add your handling code here:
        
        try{            
        int  i = Integer.parseInt(tablo.getValueAt(tablo.getSelectedRow(), 1).toString());
      
        dbo.dealSave kontrat= new dbo.dealSave();
            ResultSet klm=kontrat.contractview(i);
            
                    try{
                        while(klm.next()){
                            java.sql.Blob myBlob = klm.getBlob("ContractDate");
                            try (java.io.InputStream myInputStream = myBlob.getBinaryStream()) {
                                String yol="C:\\temp\\"+klm.getString("ContractName");
                                FileOutputStream fos = new FileOutputStream(yol);
                                byte[] buffer = new byte[klm.getInt("ContractSize")];
                                int bytesRead = 0;
                                while ((bytesRead = myInputStream.read(buffer)) != -1) {
                                    fos.write(buffer, 0, bytesRead);
                                    fos.close();
                                }
                                if ((new File(yol)).exists()) {
                                    
                                    Process p = Runtime
                                            .getRuntime()
                                            .exec("rundll32 url.dll,FileProtocolHandler "+yol);
                                    p.waitFor();
                                }
                            }   catch (InterruptedException ex) {
                                Logger.getLogger(dealsearch.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        
                        
                    }catch(IOException | SQLException e){
                        JOptionPane.showConfirmDialog(null, " "+e.getMessage());
                    }

            
        }catch(HeadlessException | NumberFormatException e){
        JOptionPane.showConfirmDialog(null, " "+e.getMessage());
        
}
        
    }//GEN-LAST:event_contractview

    private void tabloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabloKeyReleased
        // TODO add your handling code here:
 
    }//GEN-LAST:event_tabloKeyReleased

    private void tabloMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabloMouseReleased
        // TODO add your handling code here:
                 if(evt.isPopupTrigger()){
            jPopupMenu1.show(tablo, evt.getX(),evt.getY());}
    }//GEN-LAST:event_tabloMouseReleased

    private void bgview(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgview
        // TODO add your handling code here:
        try{ 
        int  i =Integer.parseInt((tablo.getValueAt(tablo.getSelectedRow(), 1).toString()));
        dbo.dealSave kontrat= new dbo.dealSave();
            ResultSet klm=kontrat.contractview(i);
            try{
                while(klm.next()){
                    java.sql.Blob myBlob = klm.getBlob("datay"); 
                    try (java.io.InputStream myInputStream = myBlob.getBinaryStream()) {
                        String yol="C:\\temp\\"+klm.getString("FileName");
                        FileOutputStream fos = new FileOutputStream(yol);
                        byte[] buffer = new byte[klm.getInt("Length")];
                        int bytesRead = 0;
                        while ((bytesRead = myInputStream.read(buffer)) != -1) {
                            fos.write(buffer, 0, bytesRead);
                            fos.close();
                        } 
                        if ((new File(yol)).exists()) {
 
			Process p = Runtime
			   .getRuntime()
			   .exec("rundll32 url.dll,FileProtocolHandler "+yol);
			p.waitFor();
                    } 
                }   catch (InterruptedException ex) { 
                        Logger.getLogger(dealsearch.class.getName()).log(Level.SEVERE, null, ex);
                    } 
                }    
               
            
            }catch(IOException | SQLException e){
            JOptionPane.showConfirmDialog(null, " "+e.getMessage());
            }}
            catch(HeadlessException | NumberFormatException e){
            JOptionPane.showConfirmDialog(null, " "+e.getMessage());
            }
        
    }//GEN-LAST:event_bgview

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        try{ 
        int  i =Integer.parseInt(tablo.getValueAt(tablo.getSelectedRow(), 1).toString());
        dbo.dealSave kontrat= new dbo.dealSave();
            ResultSet klm=kontrat.contractview(i);
            try{
                while(klm.next()){
                    java.sql.Blob myBlob = klm.getBlob("CBTCDate"); 
                    try (java.io.InputStream myInputStream = myBlob.getBinaryStream()) {
                        String yol="C:\\temp\\"+klm.getString("CBTCName");
                        FileOutputStream fos = new FileOutputStream(yol);
                        byte[] buffer = new byte[klm.getInt("CBTCSize")];
                        int bytesRead = 0;
                        while ((bytesRead = myInputStream.read(buffer)) != -1) {
                            fos.write(buffer, 0, bytesRead);
                            fos.close();
                        } 
                        if ((new File(yol)).exists()) {
 
			Process p = Runtime
			   .getRuntime()
			   .exec("rundll32 url.dll,FileProtocolHandler "+yol);
			p.waitFor();
                    } 
                }   catch (InterruptedException ex) { 
                        Logger.getLogger(dealsearch.class.getName()).log(Level.SEVERE, null, ex);
                    } 
                }    
               
            
            }catch(IOException | SQLException e){JOptionPane.showConfirmDialog(null, " "+e.getMessage());}
        
        }
            catch(NumberFormatException e){
              JOptionPane.showConfirmDialog(null, " "+e.getMessage());
            }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
         
        try{
            int  i =Integer.parseInt(tablo.getValueAt(tablo.getSelectedRow(), 1).toString());
        
        dbo.dealSave kontrat= new dbo.dealSave();
            ResultSet klm=kontrat.contractview(i);
            try{
                while(klm.next()){
                    java.sql.Blob myBlob = klm.getBlob("InvDate"); 
                    try (java.io.InputStream myInputStream = myBlob.getBinaryStream()) {
                        String yol="C:\\temp\\"+klm.getString("InvName");
                        FileOutputStream fos = new FileOutputStream(yol);
                        byte[] buffer = new byte[klm.getInt("InvSize")];
                        int bytesRead = 0;
                        while ((bytesRead = myInputStream.read(buffer)) != -1) {
                            fos.write(buffer, 0, bytesRead);
                            fos.close();
                        } 
                        if ((new File(yol)).exists()) {
 
			Process p = Runtime
			   .getRuntime()
			   .exec("rundll32 url.dll,FileProtocolHandler "+yol);
			p.waitFor();
                    } 
                }   catch (InterruptedException ex) { 
                        Logger.getLogger(dealsearch.class.getName()).log(Level.SEVERE, null, ex);
                    } 
                }    
               
            
            }catch(IOException | SQLException e){JOptionPane.showConfirmDialog(null, " "+e.getMessage());}
            
        }catch(HeadlessException | NumberFormatException e){JOptionPane.showConfirmDialog(null, " "+e.getMessage());}
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void viewlfc(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewlfc
        // TODO add your handling code here:
        try{ 
        int  i =Integer.parseInt(tablo.getValueAt(tablo.getSelectedRow(), 1).toString());
        dbo.dealSave kontrat= new dbo.dealSave();
            ResultSet klm=kontrat.contractview(i);
            try{
                while(klm.next()){
                    java.sql.Blob myBlob = klm.getBlob("LFCDate"); 
                    try (java.io.InputStream myInputStream = myBlob.getBinaryStream()) {
                        String yol="C:\\temp\\"+klm.getString("LFCName");
                        FileOutputStream fos = new FileOutputStream(yol);
                        byte[] buffer = new byte[klm.getInt("LFCSize")];
                        int bytesRead = 0;
                        while ((bytesRead = myInputStream.read(buffer)) != -1) {
                            fos.write(buffer, 0, bytesRead);
                            fos.close();
                        } 
                        if ((new File(yol)).exists()) {
 
			Process p = Runtime
			   .getRuntime()
			   .exec("rundll32 url.dll,FileProtocolHandler "+yol);
			p.waitFor();
                    } 
                }   catch (InterruptedException ex) { 
            JOptionPane.showConfirmDialog(null, " "+ex.getMessage());                    } 
                }    
               
            
            }catch(IOException | SQLException e){JOptionPane.showConfirmDialog(null, " "+e.getMessage());}
            
        }catch(HeadlessException | NumberFormatException e){JOptionPane.showConfirmDialog(null, " "+e.getMessage());}
    }//GEN-LAST:event_viewlfc

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        try{
        int  i =Integer.parseInt(tablo.getValueAt(tablo.getSelectedRow(), 1).toString());
        dbo.dealSave kontrat= new dbo.dealSave();
            ResultSet klm=kontrat.contractview(i);
            try{
                while(klm.next()){
                    java.sql.Blob myBlob = klm.getBlob("CBTCInvDate"); 
                    try (java.io.InputStream myInputStream = myBlob.getBinaryStream()) {
                        String yol="C:\\temp\\"+klm.getString("CBTCInvName");
                        FileOutputStream fos = new FileOutputStream(yol);
                        byte[] buffer = new byte[klm.getInt("CBTCInvSize")];
                        int bytesRead = 0;
                        while ((bytesRead = myInputStream.read(buffer)) != -1) {
                            fos.write(buffer, 0, bytesRead);
                            fos.close();
                        } 
                        if ((new File(yol)).exists()) {
 
			Process p = Runtime
			   .getRuntime()
			   .exec("rundll32 url.dll,FileProtocolHandler "+yol);
			p.waitFor();
                    } 
                }   catch (InterruptedException ex) { 
                        Logger.getLogger(dealsearch.class.getName()).log(Level.SEVERE, null, ex);
                    } 
                }    
               
            
            }catch(IOException | SQLException e){JOptionPane.showConfirmDialog(null, " "+e.getMessage());}
            
        }catch(HeadlessException | NumberFormatException e){JOptionPane.showConfirmDialog(null, " "+e.getMessage());}
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                int i=0;
        dbo.dealSave deal=new dbo.dealSave();
        ResultSet rss=deal.monthview();
                int j=deal.monthvieww();

        String [] kolonname={"Select","ID","Seller","Buyer","Start","End","Payment","BG Issue","BG Validity","Contract","BG"};
        Object veri[][]=new Object[j][11];
        try {
            while(rss.next()){
                veri[i][1]=rss.getInt("id");
                veri[i][2]=rss.getString("Seller");
                veri[i][3]=rss.getString("Buyer");
                veri[i][4]=rss.getDate("Start_Date");
                veri[i][5]=rss.getDate("End_Date");
                veri[i][6]=rss.getDate("Payment_Date");
                veri[i][7]=rss.getDate("Issue");
                veri[i][8]=rss.getDate("Validity");
                veri[i][9]=rss.getString("ContractName");
                veri[i][10]=rss.getString("Filename");           
            
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(dealsearch.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                           tablo.setModel(new DefaultTableModel(veri,kolonname)
                    {
            Class[] types = new Class [] {
                java.lang.Boolean.class,java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        
        jScrollPane1.setViewportView(tablo);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabloKeyPressed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_tabloKeyPressed

    private void tabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabloMouseClicked

               String alici;
        String satici;String searchName;
       String [] columnNames=new String [] {"ID", "Seller", "Buyer", "Start", "End"};
        alici=tablo.getValueAt(tablo.getSelectedRow(), 3).toString();
        satici=tablo.getValueAt(tablo.getSelectedRow(), 2).toString();
        if(alici.startsWith("Unit")){
        searchName=satici;
        }
        else{
        searchName=alici;
        }
        
        dbo.dealSave shortList =new dbo.dealSave();
        int satirSayisi=shortList.pastDeals(searchName);
        ResultSet sL=shortList.keyevent(searchName);
        Object devam[][] =new Object[satirSayisi][5];
        int i=0;
                        try {
                            while(sL.next()){
                                devam[i][0]=sL.getInt("id");
                                devam[i][1]=sL.getString("Seller");
                                devam[i][2]=sL.getString("Buyer");
                                devam[i][3]=sL.getDate("Start_Date");
                                devam[i][4]=sL.getDate("End_Date");

                                i++;
                            }               } catch (SQLException ex) {
                            Logger.getLogger(dealsearch.class.getName()).log(Level.SEVERE, null, ex);
                        }
        
                        jTable1.setModel(new DefaultTableModel(devam,columnNames));
                        jScrollPane2.setViewportView(jTable1);  
    }//GEN-LAST:event_tabloMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem contract;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JTable tablo;
    // End of variables declaration//GEN-END:variables
}
